### ISSUE TITLE
Alternative email text possible?

### ISSUE THREAD

**Issue by nikkialgar** [rainlab/user-plugin#173]
Is it possible to send different activation and welcome emails depending on the ID of a user group that the user is registering for? This is to achieve different relevant text depending on the user group.

My first attempt was to use the standard email templates and use {% if ... } conditions but this doesn't seem to be supported in the emails beyond simple {{ variable name }} 

Any advice/ideas would be appreciated.

**Comment by jBOKA** [comment]
You should extend the default `account` component `Account.php` and override the following function to add addictional logic:

https://github.com/rainlab/user-plugin/blob/master/components/Account.php#L363

Either pass the whole user as a variable to use twig `if` statements (you should consider who has access to the email templates then, since this gives access to the whole user within the template).

Better to put the logic regarding groups into the overriding function.
