### ISSUE TITLE
Send notification Email to new user created from Back-end

### ISSUE THREAD

**Issue by vdellangela** [rainlab/user-plugin#174]
Hi,

I'm looking to restrict the user registrations.
My idea is to only allow user to log in and to create them directly from the back-end.

Would it be possible to let them know by email once they have been created?
So when I create a new user in the Back-end it would send an email notification for letting them now they can connect to the website.

Many Thanks!

**Comment by vdellangela** [comment]
This is confusing because when I look at the file /modules/backend/models/User.php, I can see the function afterCreate that is use to send an email.
However this seems to only be working when a user is created on a web page and not directly from the backend.

**Comment by Al-Q** [comment]
Ah, that explains it! It has to be *user-registration* rather than *backend-registration* to trigger the *user-activation* email. I have this problem too. I've posted a question at [RainLab.user -- No activation email is sent to new user](https://octobercms.com/forum/post/rainlabuser-no-activation-email-is-sent-to-new-user) -- 47 views and no reply so far ;)

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
