### ISSUE TITLE
Registration bug when mail driver not configured

### ISSUE THREAD

**Issue by LukeTowers** [rainlab/user-plugin#189]
If you attempt to register an account without a mail driver configured or MAIL_PRETEND set to true, you will get the following error popup when you make the registration request:
```
Connection could not be established with host [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]" on line 269 of vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
```
Shouldn't there be some form of error handling in the email notification code?

**Comment by daftspunk** [comment]
I don't think so? The app failed to send mail, when the app is directed to send mail. This error tells you perfectly what the problem is, and you should probably fix it.

When [debug mode is off](http://octobercms.com/docs/setup/configuration#debug-mode), this would appear as a generic error message, with the underlying error available in the error log.

**Comment by daftspunk** [comment]
Something unrelated, if this is a bug report, it lacks a clear expectation -- check the contribution guidelines on how to report bugs. If not, it is a good question =)

**Comment by LukeTowers** [comment]
My bad, this was more of a question than a bug report. Thanks for the clarification!
