### ISSUE TITLE
How to "unsuspend" users

### ISSUE THREAD

**Issue by mpenna** [rainlab/user-plugin#240]
When throttling is set to ON, is there a way to (manually/forcefully) "unsuspend" users that have been blocked out from logging in because of too many attempts? Apparently there's not interface for this in the backend. And regarding the duration of this suspension, where can it be configured?

**Comment by bhargavy** [comment]
+1 
This is required.

**Comment by Asinox** [comment]
+1

**Comment by LukeTowers** [comment]
Feature requests as issues are only acceptable if you are using it as a pre-PR communication. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. These feature requests are absolute lowest priority for us, they may be gotten to in time. However there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
