### ISSUE TITLE
Potentially unregister new users if the AJAX request fails

### ISSUE THREAD

**Issue by SchneiderDe** [rainlab/user-plugin#241]
Hello,

In the current version, a user is not mapped to any group at all after he submits his registration form, unfortunately, although two default groups exists. One can attach an user in Guest User at least to make sure that all permissions are reduced to minimum and could not be overwritten somehow.

I added Event::listen in the Plugin.php by adding $user->groups()->attach(9); , where Group 9 = NotActivated. This works. I did not like this method of adding in the Event boot. I wanted to attach a user to a new Group "NotActivated" after submission of registration form, I added after the line 208 as under:

Line 208: $user = Auth::register($data, $automaticActivation);
Line 209: $user->addUserGroup('notactivated');

I had just started to experiment here and wanted to understand. After pressing SUBMIT, it throws an error because addUserGroup is wrong. It appeared in the frontend that the form was not submitted. However, the form was in fact submitted in the backend even though the function register() was interrupted somewhere in the middle during the processing.

**This demonstrate that an Ajax register form is submitted before it throws an error.**

This should not happen. What ever was the case of error,  either it submits or it should not. If the entire function is not executed, then the form cannot not submitted. It appears that the logic needs to be revised. It could be:

if (error == 1) { do not submit; } else { submit; }

This is currently NOT the case. When it comes to submission of Frontend forms, this issue becomes important.

**Comment by LukeTowers** [comment]
@SchneiderDe You should be able to utilize the newly added `rainlab.user.register` global element from #250 to to add your user group automatically. 

In regards to the user being registered when the AJAX request fails, that is because the actual line where the user is registered to the system is here:
```
$user = Auth::register($data, $automaticActivation);
```
As long as nothing happens there, the user will be successfully registered. As it stood prior to this, nothing in the code would have triggered an AJAX failure after that line, so that wasn't a concern.

Now that there is the potential for users to have custom code hooked into the `rainlab.user.register` event, perhaps we need to add something to the exception handling code to unregister the user if it has been registered and then an exception is thrown. Perhaps controlled via a setting ala. `remove_failed_registrations`?

@daftspunk do you have any input on the above paragraph?

**Comment by daftspunk** [comment]
I haven't read all of this, but it sounds like we need to be using a `Db::transaction`?

**Comment by LukeTowers** [comment]
If so, it'd be within the Auth::register method

**Comment by daftspunk** [comment]
Can confirm this is what's needed?

**Comment by LukeTowers** [comment]
@SchneiderDe How does my suggestion sound to you?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
