### ISSUE TITLE
login/register doesn't work on a server while it was working on a localhost

### ISSUE THREAD

**Issue by krzysztofjagiello** [rainlab/user-plugin#255]
Hey,

I have a problem:
login/register doesn't work on a server while it was working on a localhost (the same code, the same components, the same template) - this is my login page collidoor.com/login.  Could you please help?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

Although, on an initial glance at your situation it appears that you are missing jQuery from your link posted, as this error message is displayed in the developer tools console:
```
Uncaught Error: The jQuery library is not loaded. The OctoberCMS framework cannot be initialized. at framework.js:9
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
