### ISSUE TITLE
Add more fields into register form, how?

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#256]
Hello guys, i know that i can use the Auth Facade, in this way:

`$user = Auth::register([...]);`

to save extra data (fields), but i would like to know if there is another way to use extra fields into my register form without use an "extra plugin" for that or without use the Auth Facade when my user table have extra fields.

Thank you!

**Comment by LukeTowers** [comment]
The plugin just dumps whatever was sent via`$_POST` to the register method (https://github.com/rainlab/user-plugin/blob/master/components/Account.php#L224), so just add the fields to the markup of partial that displays the form by [overriding the partial in your theme](http://octobercms.com/docs/cms/components#customizing-default-markup) and make sure that you have specified that those fields are `fillable` in the User model by extending it from a plugin: https://github.com/rainlab/user-plugin/blob/master/models/User.php#L43

In essence, you will not be able to use extra fields on the register form and have them save to your database unless you build a plugin that extends this one. It's really not that hard to do, and there are already a few examples that you could reference when building your own.

In order to have extra information be entered and saved on registration, you're going to need two things:
1. A way to collect that information (easily accomplished through the use of [overriding the partial in your theme](http://octobercms.com/docs/cms/components#customizing-default-markup)),
2. A place to store that information (more difficult, requires [database migrations](http://octobercms.com/docs/database/structure) to be run)
3. A way to connect the collected information to that storage method. Whether that's using the transportation method already being used (`Auth::register($_POST)` essentially) and registering the variables that are allowed to be mass-assignable in the RainLab\User\Models\User model; or by listening to the **rainlab.user.register** event and saving your extra data where it needs to go - it's your choice. Both methods will require a custom plugin built though.

**Comment by Asinox** [comment]
Thank you @LukeTowers
