### ISSUE TITLE
Session redirect does not works

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/user-plugin#273]
Session redirect does not works. When I'm on "secured" page and I'm not logged in, it does not redirect.

Steps to reproduce:
- install fresh October login
- udpate CMS (Build 419)
- install RainLab.User plugin from CMS
- create new page `Test` in file `test.htm`
- insert Session component, select Allow only: Users, Redirect to: Subpage
- open test page and it will not redirect

Maybe related to: #258 

PHP 7.1.5

**Comment by mbaxter91288** [comment]
I have the same issue. I am pulling the plugin in from composer. When installing from marketplace via a clean install, the issue is not there. I noticed in the `Session.php` component, the redirect code is in `public function init()` and if you change to `public function onRun()` this works. I also noticed, the fresh install from Marketplace has the code in `public function onRun()` and not `init`

**Comment by daftspunk** [comment]
Not sure I like this solution. It breaks too much.

Instead we need to push the logic to a "checkUserCanAccess" method or something like this

- In onRun() we perform a redirect if user cannot access
- In init() we check if `Request::ajax()` and return Response::make('Access denied', 403)

**Comment by daftspunk** [comment]
Code in previous comment implemented here https://github.com/rainlab/user-plugin/commit/13cb46b4add6ed80146ed5eb304ddfbbf28090b1

**Comment by LukeTowers** [comment]
Thanks @daftspunk!

**Comment by mbaxter91288** [comment]
Thanks @daftspunk

**Comment by vojtasvoboda** [comment]
Thanks @daftspunk, tested now with fresh Build 420 on PHP 7.1.7 and works well!
