### ISSUE TITLE
`Auth::check()` always false

### ISSUE THREAD

**Issue by mmvcode** [rainlab/user-plugin#281]
When using the `RainLab\User\Classes\AuthMiddleware` middleware to guard custom routes, the `Auth::check()` method always returns `false`, even if the user is logged in.

Example in plugin routes.php:

```
Route::group(['middleware' => 'RainLab\User\Classes\AuthMiddleware'], function () {
    Route::post('/api/user/messages', '\Dgl\User\Controllers\Messages@onSendMessage');
    Route::get('/api/messages/unread', '\Dgl\User\Controllers\Messages@unread');
});
```

The response is always "Forbidden".

OctoberCMS build: `421`
Laravel version: `5.5`
User Plugin Version: `1.4.1 `

**Comment by mmvcode** [comment]
Need to use the web `middleware` instead, my bad.

**Comment by malcolm-bklyn** [comment]
Hi @mmvcode , Can you explain what you did to resolve this?

**Comment by shoguniphicus** [comment]
After updating to newer version of RainLab/User.
All of my custom HTTP API no longer detects the user session properly.

To fix it, will need to use web middleware like @mmvcode had mentioned.
Just do

->middleware('web') on all of your custom API endpoints in routes.php

**Comment by adc91** [comment]
@LukeTowers It would be interesting to solve this problem since it is not detecting the sessions as explained by @mmvcode 

It has also happened to me that when making ajax calls (either post or get) it does not detect the logged in user.

The only solution that has worked for me is to instantiate Account.php inside the Controller or Model where I need the user's data.

**Comment by LukeTowers** [comment]
@adc91 this is a result of Laravel switching to only starting sessions on some routes (routes with the `web` middleware attached) as of 5.5.
