### ISSUE TITLE
Can not login when use Routes.php

### ISSUE THREAD

**Issue by buuug7** [rainlab/user-plugin#286]
October build 419  

in my routes.php 
```
Route::get('/test-login', function () {
    $user = \RainLab\User\Models\User::findByEmail('youpp@126.com');
    \RainLab\User\Facades\Auth::login($user);
    return \Illuminate\Support\Facades\Redirect::to('/');
});
```
it not work.  
but used in  page or component, it work well
```
title = 'test'
url = '/test'
layout= 'default'
==
function onStart(){
$user = \RainLab\User\Models\User::findByEmail('youpp@126.com');
\RainLab\User\Facades\Auth::login($user);
}
==

<div class="container my-5">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid culpa dignissimos molestias nobis, possimus praesentium quae quam voluptatum? Adipisci blanditiis facere ipsam molestiae, molestias necessitatibus nulla obcaecati repudiandae sed suscipit.
</div>
```

**Comment by LukeTowers** [comment]
Are you 110% positive you are on build 419? Because this is something that affects Laravel 5.5 (i.e. Build 420+). There is a note in the Release Note for Build 420 about it, essentially it boils down to the fact that Laravel stopped session handling all routes and you now have to add the `web` middleware explicitly to any route that requires session handling.

**Comment by buuug7** [comment]
@LukeTowers ok

**Comment by buuug7** [comment]
if set `edgeUpdates' => true` of `config/cms.php`, then run `php artisan october:util set build`, it will show show newest build version of `build 424`

**Comment by LukeTowers** [comment]
Yes, that's an artifact of how the set build command works (basically just polls the gateway server to get the latest build number)
