### ISSUE TITLE
Unknown "partial" tag in "__string_template__***" vendor\twig\twig\lib\Twig\Parser.php

### ISSUE THREAD

**Issue by bekerov** [rainlab/user-plugin#307]
Have this error on clear install.

I installed octobercms via october and rainlab user-plugin via backend and use default theme.
After login i try reset password and get error:

`"Unknown "partial" tag in "__string_template__069e2a3026e2e4aa38c19a91af445a65122025782fad288c8085221227d5cd9b" at line 7." on line 181 of C:\Users\ADMIN\Desktop\Projects\Public\p_v2\october\vendor\twig\twig\lib\Twig\Parser.php`

how i can fix this problem?

Installed plugins 

Blog 1.2.19
User 1.4.5
I cant find octobercms version but install it today.

**Comment by LukeTowers** [comment]
Does this happen even after running `php artisan cache:clear`?

**Comment by cjayx** [comment]
I have also encountered this problem. 

In my case, I was parsing twig template using `Twig::parse` facade. After parsing I wanted to send mail using `Mail::send` facade using my own mail template (with default layout having `partial` tag). I don't know what's causing it exactly, but if you use `Twig::parse` before sending mail, the internal markup manager somehow doesn't register `MailPartialTokenParser`.

My quick workaround was to forget twig instances after using `Twig::parse` to let Mail facade recreate them:

```php
\App::forgetInstance('parse.twig');
\App::forgetInstance('twig.environment');
```

Here are the versions of october I am using:

```
october/backend v1.0.432
october/cms     v1.0.432
october/rain    v1.0.434
october/system  v1.0.432
```

**Comment by LukeTowers** [comment]
@cjayx that makes sense. The MailTokenParser only gets registered in the process of rendering a mail template: https://github.com/octobercms/october/blob/master/modules/system/classes/MailManager.php#L289-L291

**Comment by LukeTowers** [comment]
@ronogrimen yes, the issue is that you are using Build 419 with a newer version of this plugin that doesn't support Build 419. 420 was the upgrade to Laravel 5.5 so a few things changed but we kept breaking changes to a minimum. See http://octobercms.com/support/article/rn-9 for upgrade details.

I highly recommend that you do the upgrade now so that you can prevent more issues in the future. Your build of October is just going to keep on getting more and more out of date if you don't update it now and it's going to cause issues for you in the future.

**Comment by ronogrimen** [comment]
@LukeTowers I updated it to the latest version and almost all of the problems are solved. Thank you for this, really appreciated.

**Comment by LukeTowers** [comment]
@ronogrimen not a problem, happy to help!
