### ISSUE TITLE
Auth::check() always returns false in custom plugin routes php

### ISSUE THREAD

**Issue by ncarpo** [rainlab/user-plugin#337]
Im using Rainlab user plugin on a project and I have a routes.php file in a custom plugin with an entry for `Route::get('/download/{file}', 'Impelling\School\Controllers\DownloadsController@download');`

In my download method on downloadscontroller I want to do `Auth::check()` but it returns false even though a 'user_auth' session exists - can I not use the Auth facade at this point?

I have tried both  `use Auth;` and `use \Rainlab\User\Facades\Auth;` but the check() method always returns false.

I also tried running the route through middleware, and using the Auth::check() in the handler on that but still, always returns false.

However I created a october cms page, and added the same code in a `onInit` function in the code block, and Auth::check() works as expected.

Am I missing something?

**Comment by LukeTowers** [comment]
For anyone else curious about this, since @ncarpo didn't post the solution, the answer is that Laravel doesn't include the `web` middleware by default on all routes; so if you have a route that needs access to the session data at all you need to attach the `web` middleware by adding `->middleware(['web'])` to your route definition.

**Comment by ncarpo** [comment]
Oops. Sorry. Could this be explained in the docs somewhere.

**Comment by LukeTowers** [comment]
@ncarpo I'd appreciate a PR to octobercms/docs in an appropriate location. It was mentioned in https://octobercms.com/support/article/rn-9 but not everyone is going to read that.
