### ISSUE TITLE
User groups ?

### ISSUE THREAD

**Issue by tplessis** [rainlab/user-plugin#34]
Hi,

User groups exists in the core code of october (October\Rain\Database\Model), but are never used because tables does not exists in my database...

Why ?

**Comment by SaifurRahmanMohsin** [comment]
It's actually commented out if you see [here](https://github.com/octobercms/library/blob/0ab222f/src/Database/Model.php#L91-L93) so I don't think it's supported. I checked the older commits and I believe this was more of an example code rather than something October supports internally. You can already do user-based permissions so I don't think user grouping is necessary. Besides user-plugin isn't designed for user roles. You can use the [Roles plugin](http://octobercms.com/plugin/shahiemseymor-roles) to achieve that.

**Comment by daftspunk** [comment]
User groups have since been added.
