### ISSUE TITLE
Direct a registered user to a temporary welcome page till he/she has not activated the account

### ISSUE THREAD

**Issue by Mins17** [rainlab/user-plugin#368]
I have kept the activation necessary for the users.
But after they register, they remain on the login page.
I want to direct them to a temporary welcome page after registration, telling them to activate first to login to home page.
Please tell how to achieve this.

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/ <-- This is usually the best.

**Comment by Mins17** [comment]
ok. Thanks.
