### ISSUE TITLE
Refresh page after login not working

### ISSUE THREAD

**Issue by pleswi** [rainlab/user-plugin#385]
Some days ago I noticed "no refresh action" after login. 
In plugin it was set "refresh page". I switched to "no action" and it helped and worked. But after upgrade to 1.4.7 it not works again. I switched back to "refresh page" settings, but nothing happend.
Login work correctly - if manually refresh the page , user is logged in. 
Redirect to specific page works correctly.
Refresh page not working. 

Chrome, FF. Edge.....

**Comment by bennothommo** [comment]
@pleswi @Ladylain I think this may be because of this PR: https://github.com/rainlab/user-plugin/pull/383.

Both an empty string value (for the `- refresh page -` redirect option)  and a string `0` (for the `- no redirect -` option) are considered to be `true` when used with the `empty` method.

@Ladylain your fix may cause some issues with the other user actions (ie. on updating the user, or when the activation email is sent). I think a more suitable fix might be to look for those two values explicitly, and to check for the property AFTER seeing if there's a POST value for `redirect` first (ie. move the post value check in the second half of the `makeRedirection` method above the property check).

Would you be interested in trying that fix for us?

**Comment by Ladylain** [comment]
Hello, @bennothommo , i've tried this #387 and it works on my side for - no redirect - and - refresh - option 

is it ok for you ?

**Comment by bennothommo** [comment]
Fixed as of https://github.com/rainlab/user-plugin/commit/ba27e63dd2738ffe3788da8e5a69b85dfcfd6e52.

**Comment by pleswi** [comment]
Great, it's work ! Thanks to all.
