### ISSUE TITLE
Add CSRF token to default component partials

### ISSUE THREAD

**Issue by ajmanco** [rainlab/user-plugin#388]
HI . Thanks for this nice plugin . but i dont see any csrf token in login and register form . where is it ? and how can i add and use csrf token in this plugin for login and register form ?

thanks

**Comment by LukeTowers** [comment]
@ajmanco you can do one of two things, either override the component partials (https://octobercms.com/docs/cms/components#overriding-partials) or you can create a PR to change all the partials to use the `form_ajax()` Twig helper instead of using hardcoded `<form data-request="onRequestName">` elements. See `form_ajax()` on https://octobercms.com/docs/markup/function-form

**Comment by ajmanco** [comment]
@luketowers  Thanks for you reply . But i have 2 question now .
 1: why this plugin dont use this laravel default features ?! And is it enaugh secure ?
2 :  if i override the component partials or create forms with ajax and custom form , will it secure enaugh ?

**Comment by bennothommo** [comment]
Fixed as of https://github.com/rainlab/user-plugin/commit/c1679ba4c4745cb216ec44b5b4cc28cc98c850aa.

@ajmanco, in response to your questions to @LukeTowers:
1. Whilst we use Laravel as a base framework, our scope of features is different to Laravel, so we've had to do things differently in some aspects. Rest assured that we take security very seriously.
2. If you override the partials and components with your own, you're effectively making yourself responsible for the security of that functionality. So it's as secure as you make it ;)
