### ISSUE TITLE
Standard Profile update form Full Name field issue

### ISSUE THREAD

**Issue by SplicedWeb** [rainlab/user-plugin#389]
Installed this recently and realised that the standard profile field states "Full Name" on front end but updates only the "Name" field in the backend - should this not update Name and Surname?

**Comment by LukeTowers** [comment]
By default the plugin only uses the name field. The surname column exists because it's present in the base user implementation that this plugin utilizes but if you want to use it then you'll need to extend the account component to display and update it. Names are notoriously difficult to get right from a programming standpoint given the vast variations in how names work between cultures, so it's generally just easier to let the user pick what name they want to be called by and store it in one column unless you have a specific need for the first name and surname to be separate (and know that all your users have names that fit that pattern).

**Comment by SplicedWeb** [comment]
Thanks Luke.
