### ISSUE TITLE
role_id does not have a standard value

### ISSUE THREAD

**Issue by rowild** [rainlab/user-plugin#406]
I follow along this tutorial (which is from January 2017, so i might be out-of-date). When implementing the "Register" page, Ii get this error upon trying to register a new account:
```
SQLSTATE[HY000]: General error: 1364 Field 'role_id' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `persist_code`, `username`, `updated_at`, `created_at`) values (FirstName LastName, main@email.org, $2y$10$pVgf3b3maq1p2LUMMoXfdeaiIIiBQIodtSv3DbQhPNigaMRaTHCwm, , name@email.org, 2019-09-24 10:23:59, 2019-09-24 10:23:59))" on line 664 of /path/to/october/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```
Being kind-of-new (at least unexperienced) to (with) OctoberCMS and Laravel, I have no idea, what to do.

**Comment by LukeTowers** [comment]
@rowild what tutorial? Also, this plugin does not use a `role_id` column on the database table, are you trying to interact with Backend Users (BackendAuth) instead?

**Comment by rowild** [comment]
Sorry, it seems I forgot to add the youtube link - here it is:
https://www.youtube.com/watch?v=n6gvR0NZ1h8&list=PLfQvk5RK_e-Zim57m_CptCXYlgFT7P_sv&index=2

The problem is solved in the meantime, because I uninstalled all plugins and re-installed only the ones I needed again (via artisan). Unfortunately I cannot say, which plugin caused the problem (I have a hunch that it was "newride/headless", but I am not sure, because I also deleted some plugins immediately without checking the scripts. Maybe a lovata plugin...)

However: Let's assume another plugin adds such a role_id field again - do I have to adapt something in this extension?

Thank you!

**Comment by LukeTowers** [comment]
@rowild if a plugin adds that column without allowing for that value to be populated if it doesn't exist then it's a crappy plugin. Basically to give you some background to help you in the future though what happened was a plugin added the `role_id` column to the database without specifying that it could be `null` or providing a default value for it. Thus, when you try to create a User record, that `role_id` value has to be populated with something, it cannot be null and it can't be empty. So if it ever happens in the future, either remove the plugin that's adding the `role_id` column, get it fixed so that it does allow for null or empty values, or provide your own default values in your user registration logic.

**Comment by rowild** [comment]
Thank you! I indeed manipulated the database directly by allowing a `null` value. 
I just checked again - the plugin causing that trouble is this one:
`https://octobercms.com/plugin/vdomah-roles`.
It does mention that it does not require rainlab/user, but lovata/buddies, though (never tested that combi). And it also says in the 1.2.22 changelog that role_id is set to be nullable. Well... IMO this ticket can be closed.

Thank you very much for your feedback and tips!
