### ISSUE TITLE
last_seen is not set immediately after a newly registered user logs in

### ISSUE THREAD

**Issue by jonasva** [rainlab/user-plugin#428]
When a user registers and immediately logs in afterwards, their `last_seen` value will be null for the first 5 minutes of their account's existence. The logic for that is here: https://github.com/rainlab/user-plugin/blob/9113f843bdda6f98f1f5124af0809c52861edd67/models/User.php#L434

I know 5 minutes is a short time, but it actually already caused some confusion with users for a project I'm developing on. 

Possible solutions:
- Return created_at - 6 minutes as fallback in the [getLastSeen](https://github.com/rainlab/user-plugin/blob/master/models/User.php#L443) function so it'll trigger the `touchLastSeen` function immediately. 
- Set `last_seen` on `afterLogin`, but might cause impersonating users to set `last_seen` seen timestamps as well. 

Let me know your thoughts. I can help with a pull request if needed.

**Comment by bennothommo** [comment]
@jonasva I'm not quite sure this is a bug, per se. The 5 minute window is there so that the `last_seen` field isn't getting constantly written to on each request (through `Auth::user()`). The fact that `last_seen` is `null` for the first 5 minutes isn't a problem - it's probably better to use the `getLastSeen()` method so that the `created_at` time is used if `last_seen` is `null`.

Would you be able to explain your use case so that we can determine if there's a particular usage that we are not covering?

**Comment by jonasva** [comment]
My case was about a user reporting they had registered, activated their account and logged into the site and did some actions. A colleague of mine then accessed the CMS, and checked the users list. There was nothing being displayed in the "last seen" column for that user, so they assumed that user never logged into the site. That caused some confusion which I had to clear up by checking the database directly. It's not a big problem, but I can imagine more CMS admins getting confused over it.

**Comment by bennothommo** [comment]
@jonasva Thanks for the clarification. If you are interested in submitting a PR that updates the `last_seen` timestamp on logging in (unless the user is being impersonated), we would be happy to consider it.

**Comment by daftspunk** [comment]
Fixed v1.5.5
