### ISSUE TITLE
Register Component Only Works Sometimes

### ISSUE THREAD

**Issue by bbenner7635** [rainlab/user-plugin#440]
**Problem:**
Recently I have been having an issue where a few users have reported not being able to create an account despite receiving the confirmation message that their account has been created. When checking the Users tab for October, their account is not shown at all. However, I have tried replicating the issue by using their same exact login information, but the account creation works on my end.

Again, this issue is not widespread but has only occurred with a few people.

Overridden code for submit button in register.htm partial:
```
<div class = "text-center" style = "padding-top: 5px;">
            <button onclick="confirmEmail(); window.location.href='https://risenetwork.net/sign-in';" type="submit" class="btn btn-lg btn-primary" style = "border-radius: 50px;">Start 1-month Free Trial</button>
        </div>
        <script>
            function confirmEmail() {
              alert("Please check your email inbox for a confirmation email. Be sure to check your spam folder!");
            }
        </script>
```

**Comment by LukeTowers** [comment]
Sounds more like an issue with your specific setup and some user's browsers where the AJAX request to submit their details is never fired before the onclick is fired. What you should be doing instead is putting your onclick code in the `data-request-success` attribute so that you can be sure that the AJAX request has completely successfully before showing them the message that it has and redirecting them away.
