### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by DivineHeir** [rainlab/user-plugin#441]
Update failed

"SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs (SQL: alter table `users` add `created_ip_address` varchar(255) null, add `last_ip_address` varchar(255) null)" on line 664 of

**Comment by bennothommo** [comment]
@DivineHeir that particular SQL error is caused by a configuration issue with your MySQL/MariaDB database server. It can be the result of having too many columns in the `users` table, if you have installed plugins which have added columns to the users table, or if you've made manual changes to the table.

Please see the following:
- https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/
- https://stackoverflow.com/questions/22637733/mysql-error-code-1118-row-size-too-large-8126-changing-some-columns-to-te/33655143
