### ISSUE TITLE
How to change rainlab.user::mail.invite to have activation link

### ISSUE THREAD

**Issue by Artful-dodger** [rainlab/user-plugin#452]
I am using rainlabs user plugin but I do not allow users to register but I add new users manually but I still want new users to activate their account I thought I could just change the mail.invite template to

Hello {{ name }}

A user account has been created for you. Please use the following login and password to sign in:

`{% partial 'panel' body %}
- Login: `{{ login }}`
- Password: `{{ password|raw }}`
{% endpartial %}

We need to verify that this is your email address.

Please click the link below to confirm your account:

{% partial 'button' url=link type='positive' body %}
Confirm account
{% endpartial %}`

After signing in you should change your password as soon as possible.

which partially works but the button does not include the activation URL any more is there a better solution for this or will I need to alter the plugin

**Comment by mjauvin** [comment]
This is not so simple. The link will need to point to a page which has the Account component in order to activate the account. This logic is only implemented in the Account component.

You could add the link using the `rainlab.user.getNotificationVars` event, but the link would have to be generated manually.

**Comment by daftspunk** [comment]
This should be solvable by setting the `activationPage` property on the component.

Fixed by #472
