### ISSUE TITLE
How remove/delete UserGroup from User after submitting Frontend-Form

### ISSUE THREAD

**Issue by joelfriesecke** [rainlab/user-plugin#464]
I understood that i was using 
```php
$user->groups()->add($group);
```
i can add a group to a user,
but how can i remove the groups again automatically if i delete the user?
```php
$user->groups()->remove(); or $user->groups()->delete();
```
not working
Thanks for helping!

**Comment by LukeTowers** [comment]
If you want to remove a single group, just use `remove()`. If you want to clean up all the relationships after deleting one of the related records, this is already done automatically here (https://github.com/octobercms/library/blob/develop/src/Database/Model.php#L926-L933). 

The reason it's not in your case is that the User model implements the SoftDelete trait, which means that auto-cleanup method is never called because it's possible for user records to be undeleted. If you'd like to permanently delete a user record (and thus also run the auto cleanup logic) you need to call `$user->forceDelete()`
