### ISSUE TITLE
User Expiry

### ISSUE THREAD

**Issue by cydrickn** [rainlab/user-plugin#52]
Hi,

Can you add some setting.
The setting is about the expiry of the user.
If the user is logined and the browser is close and open again the browser, the user is still logined.
I want to have that if user is logined and if the browser is closed the cookie must also expired.
We can do this via editing the session.php config in core.
But how to change it without changing the core.

**Comment by jakerator** [comment]
I still have the same issue. Sessiosn lifetime settings are not applying from app/config/session.php config file. It is alreays logged in whatever I set in sessiosn config. Is this a bug?

**Comment by LukeTowers** [comment]
@jakerator Not really, more of a lack of support for configurable session lifetimes on these users. I need to add support for it in a project that I'm working on right now though so I'll make a PR for it some point soon.

**Comment by joepmeeuwissen** [comment]
Will this feature be added any time soon? Thanks!

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
