### ISSUE TITLE
[Suggestion] Re-activation required after email change

### ISSUE THREAD

**Issue by xyrofreeze** [rainlab/user-plugin#85]
Hi. A suggestion if the Settings is set to 'User Activation Mode'.

If a User changes his email address, which is used for signing in. His account should be de-activated and a new Activation email be sent to this new email address.

Thanks

**Comment by jBOKA** [comment]
Scenario:

A user changes his email address, makes a mistake, wrong email is saved. If the user was deactivated upon email change, he wouldn't be able to login and also couldn't receive a reactivation mail, since the new **wrong** mail is stored already.

This would require a new table to withhold the old email etc etc. and therefore need some thought I guess.

Maybe read up on how other sites handle this. I'm not sure about it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
